export const stockData = [
  {
    id: 1,
    name: "bibit kayu putih",
    image: "./images/kayuputih.jpeg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Komunitas Pecinta Alam Damai",
    location: "Kutai Barat",
    price: 100000,
  },
  {
    id: 2,
    name: "bibit pohon jati",
    image: "./images/jati.jpeg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Himpala ITENAS",
    location: "Bandung, Jawa Barat",
    price: 150000,
  },
  {
    id: 3,
    name: "bibit Pohon Mahoni",
    image: "./images/mahoni.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Green Surabaya",
    location: "Surabaya, Jawa Timur",
    price: 200000,
  },
  {
    id: 4,
    name: "bibit pohon cendana",
    image: "./images/cendana.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Remaja SMA Pecinta Alam",
    location: "Magetan, Jawa Timur",
    price: 130000,
  },
  {
    id: 5,
    name: "bibit Gaharu",
    image: "./images/gaharu.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Komunitas Pecinta Alam Damai",
    location: "Kutai Barat",
    price: 150000,
  },
  {
    id: 6,
    name: "bibit pohon palm",
    image: "./images/palm.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Khatulistiwa Dairi",
    location: "Pontianak",
    price: 300000,
  },
  {
    id: 7,
    name: "bibit Pohon Sengon",
    image: "./images/sengon.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Cyber Adventure Indonesia",
    location: "Kalimantan",
    price: 300000,
  },
  {
    id: 8,
    name: "bibit Pohon Ulin",
    image: "./images/ulin.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    organization: "Kesatuan Pengelola Hutan",
    location: "Tanah Laut",
    price: 100000,
  },
];
